title: ByeHarper
tagline: Browser add-on that replaces Stephen Harper with Some Fear Mongering Shithead
fullurl: "http://fearmongeringshithead.ca/" #used for fb share content
fbsharetext: Browser add-on that replaces Stephen Harper with Some Fear Mongering Shithead. Available for Chrome and Firefox.
fbshareimg: http://fearmongeringshithead.ca/meanharper.png
